import { useEffect, useRef } from "react";
import * as d3 from "d3";
export default function ViewSchoolPage() {
  return (
    <>
      <svg
        width={"100%"}
        height={"6rem"}
        style={{ backgroundColor: "#d9d9d9" }}
      >
        <rect
          x={0}
          y={"1rem"}
          width={"1rem"}
          height={"4rem"}
          fill={"#14A65B"}
        />
        <rect
          x={"12rem"}
          y={"5rem"}
          width={"4rem"}
          height={"1rem"}
          fill={"#14A65B"}
        />
        <rect
          x={"22rem"}
          y={"5rem"}
          width={"4rem"}
          height={"1rem"}
          fill={"#14A65B"}
        />
        <rect
          x={"3rem"}
          y={0}
          width={"4rem"}
          height={"2rem"}
          fill={"#29A7E1"}
        />
        <rect
          x={"8rem"}
          y={0}
          width={"4rem"}
          height={"2rem"}
          fill={"#E71873"}
        />
      </svg>
      <svg
        width={"6rem"}
        height={"40rem"}
        style={{ backgroundColor: "#d9d9d9", marginLeft: "31.5rem" }}
      >
        <rect
          x={0}
          y={"18rem"}
          width={"1rem"}
          height={"4rem"}
          fill={"#14A65B"}
        />
        <rect
          x={0}
          y={"32rem"}
          width={"1rem"}
          height={"4rem"}
          fill={"#14A65B"}
        />
        <rect
          x={"4rem"}
          y={'5rem'}
          width={"2rem"}
          height={"4rem"}
          fill={"#29A7E1"}
        />
        <rect
          x={"4rem"}
          y={'10rem'}
          width={"2rem"}
          height={"4rem"}
          fill={"#E71873"}
        />
         <rect
          x={"4rem"}
          y={'25rem'}
          width={"2rem"}
          height={"4rem"}
          fill={"#E71873"}
        />
      </svg>
    </>
  );
}
